E_Trading_System/Controllers/E_KartTrading/Customers/CustomerLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using E_Trading_System.Models;
namespace E_Trading_System.Controllers.E_KartTrading.Customers
{
    
        public class CustomerLoginController : Controller
        {
            // GET: Customer
            public decimal Cust_Id;
            public ActionResult Login()
            {
                return View();
            }


            private readonly E_Trading_SystemDBEntities4 db;

            public CustomerLoginController()
            {
                db = new E_Trading_SystemDBEntities4();
            }
           
            [HttpPost]
            public ActionResult Login(string email, string password)
            {

                if (IsValidCustomer(email, password))
                {
                     Cust_Id = db.Customers.Where(c => c.Customer_Email == email).Select(c => c.Customer_Id).FirstOrDefault();
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.InvalidLogin = "Invalid Customer Email or password.";
                    return View();
                }
            }

            private bool IsValidCustomer(string email, string password)
            {
                string Email = db.Customers.Where(x => x.Customer_Email == email).Select(x => x.Customer_Email).FirstOrDefault();
                string Password = db.Customers.Where(x => x.Customer_Email == email).Select(x => x.Password).FirstOrDefault();
                if (email == Email && password == Password)
                {
                    return true;
                }
                return false;
            }
        }
    }

E_Trading_System/Views/CustomerLogin/Login.cshtml
@model E_Trading_System.Models.Customer

@{
    ViewBag.Title = "Login";
}

@*<h2>Login</h2>*@

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>

    <style>


        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Poppins', sans-serif;
        }


        body {
            background-color: dimgrey;
            background: linear-gradient(to right, Grey, darkslategrey);
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
            height: 100vh;
        }


        .containerA {
            background-color: black;
            border-radius: 30px;
            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.35);
            position: relative;
            overflow: hidden;
            width: 768px;
            max-width: 100%;
            min-height: 480px;
            margin-top:60px;
        }


            .containerA p {
                font-size: 14px;
                line-height: 20px;
                letter-spacing: 0.3px;
                margin: 20px 0;
            }


            .containerA span {
                font-size: 12px;
                color: darkgrey;
            }

            .containerA a {
                color: darkgrey;
                font-size: 13px;
                text-decoration: none;
                margin: 15px 0 10px;
            }
            .containerA a:hover
            {
                color:white;
            }

            .containerA button {
                background-color: white;
                color: black;
                font-size: 12px;
                padding: 10px 45px;
                border: 1px solid transparent;
                border-radius: 8px;
                font-weight: 600;
                letter-spacing: 0.5px;
                text-transform: uppercase;
                margin-top: 10px;
                cursor: pointer;
            }
                .containerA button:hover
                {
                    background-color:antiquewhite;
                }

                .containerA button.hidden {
                    background-color: transparent;
                    border-color: #fff;
                }

            .containerA form {
                background-color: black;
                display: flex;
                align-items: center;
                justify-content: center;
                flex-direction: column;
                padding: 0 40px;
                height: 100%;
            }

            .containerA input {
                background-color: white;
                border: 2px solid grey;
                margin: 8px 0;
                padding: 10px 15px;
                font-size: 13px;
                border-radius: 8px;
                width: 100%;
                outline: none;
            }

        .form-container {
            position: absolute;
            top: 0;
            height: 100%;
            transition: all 0.6s ease-in-out;
        }

        .sign-in {
            left: 0;
            width: 50%;
            z-index: 2;
        }

        .containerA.active .sign-in {
            transform: translateX(100%);
        }

        .sign-up {
            left: 0;
            width: 50%;
            opacity: 0;
            z-index: 1;
        }
   

            .containerA.active .sign-up {
                transform: translateX(100%);
                opacity: 1;
                z-index: 5;
                animation: move 0.6s;
            }

            @@keyframes move {
                0%, 49.99% {
                    opacity: 0;
                    z-index: 1;
                }

                50%, 100% {
                    opacity: 1;
                    z-index: 5;
                }
            }

            .social-icons {
                margin: 20px 0;
            }

                .social-icons a {
                    border: 1px solid #ccc;
                    border-radius: 20%;
                    display: inline-flex;
                    justify-content: center;
                    align-items: center;
                    margin: 0 3px;
                    width: 40px;
                    height: 40px;
                }

            .toggle-container {
                position: absolute;
                top: 0;
                left: 50%;
                width: 50%;
                height: 100%;
                overflow: hidden;
                transition: all 0.6s ease-in-out;
                border-radius: 150px 0 0 100px;
                z-index: 1000;
            }

            .containerA.active .toggle-container {
                transform: translateX(-100%);
                border-radius: 0 150px 100px 0;
            }

            .toggle {
                background-color: #512da8;
                height: 100%;
                background: linear-gradient(to right,dimgrey, dimgrey);
                color: #fff;
                position: relative;
                left: -100%;
                height: 100%;
                width: 200%;
                transform: translateX(0);
                transition: all 0.6s ease-in-out;
            }

            .containerA.active .toggle {
                transform: translateX(50%);
            }

            .toggle-panel {
                position: absolute;
                width: 50%;
                height: 100%;
                display: flex;
                align-items: center;
                justify-content: center;
                flex-direction: column;
                padding: 0 30px;
                text-align: center;
                top: 0;
                transform: translateX(0);
                transition: all 0.6s ease-in-out;
            }

            .toggle-left {
                transform: translateX(-200%);
            }

            .containerA.active .toggle-left {
                transform: translateX(0);
            }

            .toggle-right {
                right: 0;
                transform: translateX(0);
            }

            .containerA.active .toggle-right {
                transform: translateX(200%);
            }
        </style>
</head>

<body>

    <div class="containerA" id="container">
        <div class="form-container sign-up">
            <form>
                @*<h1>Create Account</h1>
                <span>or use your email for registeration</span>
                <input type="text" placeholder="Name">
                <input type="email" placeholder="Email">
                <input type="password" placeholder="Password">
                <button>Sign Up</button>*@
            </form>
        </div>
        <div class="form-container sign-in">
            @*<form >
                <h1>Create Account</h1>
                <span>or use your email for registeration</span>
                <input type="text" placeholder="Name">
                <input type="email" placeholder="Email">
                <input type="password" placeholder="Password">
                <button>Sign Up</button>
            </form>*@
            <form method="post" action="@Url.Action("Login", "CustomerLogin")">
                <span><b>Email Id</b></span>
                <input type="text" id="email" name="email" required />
                @Html.ValidationMessageFor(model => model.Customer_Email)
                <span><b>Password</b></span>
                <input type="password" id="password" name="password" required/>
                @Html.ValidationMessageFor(model => model.Password)

                <a href="https://www.w3schools.com/cssref/pr_background-color.php">Forget Your Password?</a>
                <button>SignUp</button>
                @if (!string.IsNullOrEmpty(ViewBag.InvalidLogin))
                {
                    <div class="field-validation-error">@ViewBag.InvalidLogin</div>
                }
            </form>
            
        </div>
        <div class="toggle-container">
            <div class="toggle">
                <div class="toggle-panel toggle-left">
                    <h1>Welcome Back!</h1>
                    <p>Enter your personal details to use all of site features</p>
                    <button class="hidden" id="login">Sign In</button>
                </div>
                <div class="toggle-panel toggle-right">
                    <h1>Hello, USER!</h1>
                    <p>Register with your personal details to Login your Account</p>
                    <button class="hidden" id="register">Sign Up</button>
                   
                </div>
            </div>
        </div>
       
        
    


</body>

</html>